// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/5/2026, 2:18:16 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquis/erranders/barter/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/plugins/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter/website/composables/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter/website/utils/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter/website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter/website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;