// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/26/2026, 12:53:00 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquis/erranders/barter-app/barter-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/plugins/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter-app/barter-website/composables/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter-app/barter-website/utils/**/*.{js,ts,mjs}","/Users/marquis/erranders/barter-app/barter-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/erranders/barter-app/barter-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;